tabs:
  defaultTab: Контакты
  lazy:
      - Контакты
      - Общие
      - Главная страница
      - Новости
  paneCssClass:
      0: first-tab
      1: second-tab
      2: third-tab
      3: four-tab
  icons:
      Контакты: icon-phone
      Общие: icon-cogs
      Главная страница: icon-home
      Новости: icon-newspaper-o
  fields:
      phone:
          type: text
          label: Телефон
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: '+79147580525'
      t_email:
          type: email
          label: E-mail
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: 'example@mail.ru'
      open:
          type: text
          label: График работы
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: 'Ежедневно с 9:00 до 18:00'
      address:
          type: text
          label: Адрес
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: 'г. Москва'
      whatsapp:
          type: text
          label: WhatsApp
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: '79147580525'
      viber:
          type: text
          label: Viber
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: '79147580525'
      vk:
          type: text
          label: Вконтакте
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: https://vk.com
      instagram:
        type: text
        label: Instagram
        span: storm
        cssClass: col-md-4
        tab: Контакты
        placeholder: https://www.instagram.com
      twitter:
        type: text
        label: Twitter
        span: storm
        cssClass: col-md-4
        tab: Контакты
        placeholder: https://www.twitter.com
      map:
        type: textarea
        label: Код карты
        span: storm
        size: large
        cssClass: col-md-12
        tab: Контакты
        placeholder:
      site_name:
        type: text
        label: Название сайта
        default: OctoberCms
        span: full
        tab: Общие
      form_section:
        label: Секция с формой
        type: section
        tab: Общие
      form_title:
        type: text
        label: Заголовок
        span: full
        tab: Общие
      form_content:
        label: Описание
        type: richeditor
        size: large
        tab: Общие
      news_section:
        label: Секция новостей
        type: section
        tab: Новости

      news:
        type: repeater
        prompt: Добавить
        titleFrom: Новости
        form:
            fields:
                image:
                    label: Иконка
                    type: mediafinder
                    mode: image
                    imageHeight: 200
                    imageWidth: 150
                title:
                    label: Заголовок
                    type: text
                    span: full
                desc:
                    label: Описание
                    type: textarea
                    size: large
                    span: full
                date:
                    label: Дата
                    type: text
                    span: left
                    placeholder: 24.02.2021
                link:
                    label: Ссылка
                    type: text
                    span: right
                    placeholder: https://ya.ru
        tab: Новости
